# Generated by Django 5.0.3 on 2024-04-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A User with that username already exists.'}, max_length=150, null=True, verbose_name='username'),
        ),
    ]
