# Generated by Django 5.0.3 on 2024-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationotp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
